In [1]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
alpha,hidden_dim = (0.5,4)


In [11]:
from numpy import *

# y = mx + b
# m is slope, b is y-intercept
def compute_error_for_line_given_points(b, m, points):
    totalError = 0
    for i in range(0, len(points)):
        x = points[i, 0]
        y = points[i, 1]
        totalError += (y - (m * x + b)) ** 2
    return totalError / float(len(points))

def step_gradient(b_current, m_current, points, learningRate):
    b_gradient = 0
    m_gradient = 0
    N = float(len(points))
    for i in range(0, len(points)):
        x = points[i, 0]
        y = points[i, 1]
        b_gradient += -(2/N) * (y - ((m_current * x) + b_current))
        m_gradient += -(2/N) * x * (y - ((m_current * x) + b_current))
    new_b = b_current - (learningRate * b_gradient)
    new_m = m_current - (learningRate * m_gradient)
    return [new_b, new_m]

def gradient_descent_runner(points, starting_b, starting_m, learning_rate, num_iterations):
    b = starting_b
    m = starting_m
    for i in range(num_iterations):
        b, m = step_gradient(b, m, array(points), learning_rate)
    return [b, m]

def run():
    points = genfromtxt("data.csv", delimiter=",")
    learning_rate = 0.0001
    initial_b = 0 # initial y-intercept guess
    initial_m = 0 # initial slope guess
    num_iterations = 10
    print "Starting gradient descent at b = {0}, m = {1}, error = {2}".format(initial_b, initial_m, compute_error_for_line_given_points(initial_b, initial_m, points))
    print "Running..."
    [b, m] = gradient_descent_runner(points, initial_b, initial_m, learning_rate, num_iterations)
    print "After {0} iterations b = {1}, m = {2}, error = {3}".format(num_iterations, b, m, compute_error_for_line_given_points(b, m, points))

if __name__ == '__main__':
    run()

Starting gradient descent at b = 0, m = 0, error = 5565.10783448
Running...
After 10 iterations b = 0.0296393478747, m = 1.47741737555, error = 112.655851815


In [17]:
# Fitting a degree d polynomial to the data (X,y)
def fit_degree_d_poly(X,y,d):
    n = X.shape[0]
    Z = np.meshgrid(X,np.arange(d+1))[0]
    Z = Z.transpose()
    P = np.meshgrid(np.arange(d+1),np.arange(n))[0]
    W = Z**P
    coeff = find_regressor(W,y)
    return coeff
def find_regressor(X,y):
    beta = np.linalg.lstsq(X,y)[0]
    return beta 

In [18]:
import numpy as np
X = np.random.randn(4)
len(X)
X[0] = -2
X[1] = -1
X[2] = 1
X[3] = 2
print X



[-2. -1.  1.  2.]


In [19]:
Y = np.random.randn(4)
Y[0] = 2.1
Y[1] = 0.95
Y[2] = -0.96
Y[3] = -1.92
print Y

[ 2.1   0.95 -0.96 -1.92]


In [20]:
# Let's fit a degree d polynomial using the above function
d = 2
coeff = fit_degree_d_poly(X,Y,d)
poly = np.poly1d(coeff[::-1])
print coeff

[-0.03666667 -0.995       0.03166667]


In [22]:
import matplotlib.pyplot as plt
ys = poly(np.arange(X.min(),X.max(),0.01))
plt.plot(np.arange(X.min(),X.max(),0.01),ys)
plt.plot(X, Y, 'o')
#plt.plot(X_test,y_test,'+')
#plot(x, ys)
plt.ylabel('Y')
plt.xlabel('X')
plt.show()

In [8]:
print x
print np.random.randn(4)

[0.32225428, 1.84875917, 2.7404421, -0.52934847]
[-0.28659247 -1.17204296 -0.41795975  0.76444075]


[1 2 3 4]


x = np.array([-2, -1, 1, 2])
y = np.array([2.1, 0.95, -0.96, -1.92])
A = np.vstack([x, np.ones(len(x))]).T
print A
m, c = np.linalg.lstsq(A, y)[0]
print m, c

In [26]:
x = np.array([-2, -1, 1, 2]) 
y = np.array([2.1, 0.95, -0.96, -1.92]) 
A = np.vstack([x, np.ones(len(x))]).T 
print A 
m, c = np.linalg.lstsq(A, y)[0] 
print m, c

[[-2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2.  1.]]
-0.995 0.0425
